# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/work/resistor-capacitance-inductance-measurement-system/rcims/rcims.tmp/dds_v1_0_project/DDS_v1_0_project.cache/wt [current_project]
set_property parent.project_path c:/work/resistor-capacitance-inductance-measurement-system/rcims/rcims.tmp/dds_v1_0_project/DDS_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/work/Resistor-Capacitance-Inductance-Measurement-System/ip_repo/ADC_1.0
  c:/work/Resistor-Capacitance-Inductance-Measurement-System/ip_repo/DDS_1.0
  c:/work/Resistor-Capacitance-Inductance-Measurement-System/ip_repo/DDS_1.0
} [current_project]
set_property ip_output_repo c:/work/resistor-capacitance-inductance-measurement-system/rcims/rcims.tmp/dds_v1_0_project/DDS_v1_0_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  c:/work/Resistor-Capacitance-Inductance-Measurement-System/ip_repo/DDS_1.0/hdl/DDS_v1_0_S00_AXI.v
  c:/work/Resistor-Capacitance-Inductance-Measurement-System/ip_repo/DDS_1.0/hdl/DDS_v1_0.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top DDS_v1_0 -part xc7z010clg400-1


write_checkpoint -force -noxdef DDS_v1_0.dcp

catch { report_utilization -file DDS_v1_0_utilization_synth.rpt -pb DDS_v1_0_utilization_synth.pb }
