set_property IOSTANDARD LVCMOS33 [get_ports Clk_2Mhz]
set_property IOSTANDARD LVCMOS33 [get_ports MISO]
set_property IOSTANDARD LVCMOS33 [get_ports MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SCK]
set_property IOSTANDARD LVCMOS33 [get_ports adc_reset]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[15]}]

set_property PACKAGE_PIN T11 [get_ports Clk_2Mhz]
set_property PACKAGE_PIN T14 [get_ports MISO]
set_property PACKAGE_PIN U13 [get_ports MOSI]
set_property PACKAGE_PIN V12 [get_ports SCK]
set_property PACKAGE_PIN V17 [get_ports adc_reset]
set_property PACKAGE_PIN U18 [get_ports clk_in1]
set_property PACKAGE_PIN N15 [get_ports reset]

set_property PACKAGE_PIN W19 [get_ports {raw_data[0]}]
set_property PACKAGE_PIN R14 [get_ports {raw_data[1]}]
set_property PACKAGE_PIN Y17 [get_ports {raw_data[2]}]
set_property PACKAGE_PIN W15 [get_ports {raw_data[3]}]
set_property PACKAGE_PIN Y14 [get_ports {raw_data[4]}]

set_property PACKAGE_PIN P18 [get_ports {raw_data[5]}]
set_property PACKAGE_PIN U15 [get_ports {raw_data[6]}]
set_property PACKAGE_PIN P16 [get_ports {raw_data[7]}]
set_property PACKAGE_PIN U17 [get_ports {raw_data[8]}]
set_property PACKAGE_PIN V18 [get_ports {raw_data[9]}]

set_property PACKAGE_PIN T15 [get_ports {raw_data[10]}]
set_property PACKAGE_PIN V13 [get_ports {raw_data[11]}]
set_property PACKAGE_PIN W13 [get_ports {raw_data[12]}]
set_property PACKAGE_PIN U12 [get_ports {raw_data[13]}]
set_property PACKAGE_PIN T10 [get_ports {raw_data[14]}]
set_property PACKAGE_PIN A20 [get_ports {raw_data[15]}]

set_property MARK_DEBUG true [get_nets {raw_data_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[10]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[11]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[12]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[13]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[14]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[15]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[2]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[3]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[4]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[5]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[6]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[7]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[8]}]
set_property MARK_DEBUG true [get_nets {raw_data_OBUF[9]}]
set_property MARK_DEBUG true [get_nets adc_reset_OBUF]
set_property MARK_DEBUG true [get_nets SCK_OBUF]
set_property MARK_DEBUG true [get_nets MOSI_OBUF]
set_property MARK_DEBUG true [get_nets Clk_2Mhz_OBUF]
set_property MARK_DEBUG true [get_nets reset_IBUF]
set_property MARK_DEBUG true [get_nets MISO_IBUF]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/clk_wiz_0/inst/clk_in1_system_clk_wiz_0_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {raw_data_OBUF[0]} {raw_data_OBUF[1]} {raw_data_OBUF[2]} {raw_data_OBUF[3]} {raw_data_OBUF[4]} {raw_data_OBUF[5]} {raw_data_OBUF[6]} {raw_data_OBUF[7]} {raw_data_OBUF[8]} {raw_data_OBUF[9]} {raw_data_OBUF[10]} {raw_data_OBUF[11]} {raw_data_OBUF[12]} {raw_data_OBUF[13]} {raw_data_OBUF[14]} {raw_data_OBUF[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list adc_reset_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list Clk_2Mhz_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list MISO_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list MOSI_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list reset_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list SCK_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_in1_system_clk_wiz_0_0]
