# 
# Synthesis run script generated by Vivado
# 

set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.cache/wt [current_project]
set_property parent.project_path C:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.srcs/sources_1/imports/src/spi_master.v
  C:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.srcs/sources_1/imports/src/adc.v
  C:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.srcs/sources_1/imports/new/Clk_4_Div.v
  C:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.srcs/sources_1/bd/system/hdl/system_wrapper.v
}
add_files C:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files C:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.srcs/sources_1/bd/system/system.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.srcs/constrs_1/imports/new/system.xdc
set_property used_in_implementation false [get_files C:/work/Resistor-Capacitance-Inductance-Measurement-System/ADC_SPI_test/ADC_SPI_test.srcs/constrs_1/imports/new/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef system_wrapper.dcp

catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
