set_property IOSTANDARD LVCMOS33 [get_ports {m_axis_data_tdata[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {m_axis_data_tdata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {m_axis_data_tdata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {m_axis_data_tdata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {m_axis_data_tdata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {m_axis_data_tdata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {m_axis_data_tdata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {m_axis_data_tdata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports m_axis_data_tvalid]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_ADC_reset]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out]
set_property IOSTANDARD LVCMOS33 [get_ports clock_rtl]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl]

set_property PACKAGE_PIN W18 [get_ports {m_axis_data_tdata[0]}]
set_property PACKAGE_PIN P14 [get_ports {m_axis_data_tdata[1]}]
set_property PACKAGE_PIN Y16 [get_ports {m_axis_data_tdata[2]}]
set_property PACKAGE_PIN V15 [get_ports {m_axis_data_tdata[3]}]
set_property PACKAGE_PIN W14 [get_ports {m_axis_data_tdata[4]}]
set_property PACKAGE_PIN N17 [get_ports {m_axis_data_tdata[5]}]
set_property PACKAGE_PIN U14 [get_ports {m_axis_data_tdata[6]}]
set_property PACKAGE_PIN P15 [get_ports {m_axis_data_tdata[7]}]
set_property PACKAGE_PIN T16 [get_ports m_axis_data_tvalid]
set_property PACKAGE_PIN V17 [get_ports ADC_ADC_reset]
set_property PACKAGE_PIN T14 [get_ports ADC_MISO]
set_property PACKAGE_PIN U13 [get_ports ADC_MOSI]
set_property PACKAGE_PIN V12 [get_ports ADC_SCK]
set_property PACKAGE_PIN T11 [get_ports clk_out]
set_property PACKAGE_PIN U18 [get_ports clock_rtl]
set_property PACKAGE_PIN N15 [get_ports reset_rtl]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/data_byte[7]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list system_i/clk_wiz_0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/spi_master_i/ADC_Clk_2Mhz]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][0]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][1]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][2]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][3]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][4]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][5]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][6]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][7]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][8]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][9]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][10]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][11]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][12]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][13]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][14]} {system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/slv_reg0_reg[15][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/spi_master_i/ADC_MISO]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/spi_master_i/ADC_reset]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list system_i/ADC_0/inst/ADC_v1_0_S00_AXI_inst/adc_i/spi_master_i/ADC_MOSI]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_clk_out1]
