# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lcd.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_clk_wiz_0_0_1/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}]

# IP: bd/system/ip/system_sync_module_0_0_1/system_sync_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sync_module_0_0 || ORIG_REF_NAME==system_sync_module_0_0}]

# IP: bd/system/ip/system_lcd_control_module_0_0/system_lcd_control_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lcd_control_module_0_0 || ORIG_REF_NAME==system_lcd_control_module_0_0}]

# IP: bd/system/ip/system_data_combine_module_0_0_1/system_data_combine_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_data_combine_module_0_0 || ORIG_REF_NAME==system_data_combine_module_0_0}]

# IP: bd/system/ip/system_dist_mem_gen_0_0_1/system_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dist_mem_gen_0_0 || ORIG_REF_NAME==system_dist_mem_gen_0_0}]

# IP: bd/system/ip/system_rom_2_0/system_rom_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_2_0 || ORIG_REF_NAME==system_rom_2_0}]

# IP: bd/system/ip/system_rom_3_0/system_rom_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_3_0 || ORIG_REF_NAME==system_rom_3_0}]

# IP: bd/system/ip/system_rom_3_1/system_rom_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_3_1 || ORIG_REF_NAME==system_rom_3_1}]

# IP: bd/system/ip/system_rom_3_2/system_rom_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_3_2 || ORIG_REF_NAME==system_rom_3_2}]

# IP: bd/system/ip/system_rom_3_3/system_rom_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_3_3 || ORIG_REF_NAME==system_rom_3_3}]

# IP: bd/system/ip/system_rom_3_4/system_rom_3_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_3_4 || ORIG_REF_NAME==system_rom_3_4}]

# IP: bd/system/ip/system_rom_3_5/system_rom_3_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_3_5 || ORIG_REF_NAME==system_rom_3_5}]

# IP: bd/system/ip/system_rom_3_6/system_rom_3_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_3_6 || ORIG_REF_NAME==system_rom_3_6}]

# IP: bd/system/ip/system_rom_3_7/system_rom_3_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_3_7 || ORIG_REF_NAME==system_rom_3_7}]

# IP: bd/system/ip/system_rom_0_0/system_rom_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_0_0 || ORIG_REF_NAME==system_rom_0_0}]

# IP: bd/system/ip/system_rom_R_0/system_rom_R_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_R_0 || ORIG_REF_NAME==system_rom_R_0}]

# IP: bd/system/ip/system_rom_R_1/system_rom_R_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_R_1 || ORIG_REF_NAME==system_rom_R_1}]

# IP: bd/system/ip/system_rom_R_2/system_rom_R_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_R_2 || ORIG_REF_NAME==system_rom_R_2}]

# IP: bd/system/ip/system_rom_R_3/system_rom_R_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_R_3 || ORIG_REF_NAME==system_rom_R_3}]

# IP: bd/system/ip/system_rom_omega_0/system_rom_omega_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_omega_0 || ORIG_REF_NAME==system_rom_omega_0}]

# IP: bd/system/ip/system_rom_omega_1/system_rom_omega_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_omega_1 || ORIG_REF_NAME==system_rom_omega_1}]

# XDC: bd/system/ip/system_clk_wiz_0_0_1/system_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clk_wiz_0_0_1/system_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clk_wiz_0_0_1/system_clk_wiz_0_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clk_wiz_0_0_1/system_clk_wiz_0_0_ooc.xdc

# XDC: bd/system/ip/system_dist_mem_gen_0_0_1/system_dist_mem_gen_0_0_ooc.xdc

# XDC: bd/system/ip/system_rom_2_0/system_rom_2_0_ooc.xdc

# XDC: bd/system/ip/system_rom_3_0/system_rom_3_0_ooc.xdc

# XDC: bd/system/ip/system_rom_3_1/system_rom_3_1_ooc.xdc

# XDC: bd/system/ip/system_rom_3_2/system_rom_3_2_ooc.xdc

# XDC: bd/system/ip/system_rom_3_3/system_rom_3_3_ooc.xdc

# XDC: bd/system/ip/system_rom_3_4/system_rom_3_4_ooc.xdc

# XDC: bd/system/ip/system_rom_3_5/system_rom_3_5_ooc.xdc

# XDC: bd/system/ip/system_rom_3_6/system_rom_3_6_ooc.xdc

# XDC: bd/system/ip/system_rom_3_7/system_rom_3_7_ooc.xdc

# XDC: bd/system/ip/system_rom_0_0/system_rom_0_0_ooc.xdc

# XDC: bd/system/ip/system_rom_R_0/system_rom_R_0_ooc.xdc

# XDC: bd/system/ip/system_rom_R_1/system_rom_R_1_ooc.xdc

# XDC: bd/system/ip/system_rom_R_2/system_rom_R_2_ooc.xdc

# XDC: bd/system/ip/system_rom_R_3/system_rom_R_3_ooc.xdc

# XDC: bd/system/ip/system_rom_omega_0/system_rom_omega_0_ooc.xdc

# XDC: bd/system/ip/system_rom_omega_1/system_rom_omega_1_ooc.xdc

# XDC: bd/system/system_ooc.xdc
