# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/ip_repo [current_project]
set_property ip_output_repo c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/2.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/3.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/4.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/5.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/6.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/7.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/8.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/9.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/1.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/0.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/R.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/C.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/L.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/equal.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/omega.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/nF.coe
add_files c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/new/mH.coe
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/imports/new/test.v
  C:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/hdl/top_wrapper.v
}
add_files C:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/top.bd
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_clk_wiz_0_0_1/system_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_clk_wiz_0_0_1/system_clk_wiz_0_0_late.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_clk_wiz_0_0_1/system_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_dist_mem_gen_0_0_1/system_dist_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_2_0/system_rom_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_3_0/system_rom_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_3_1/system_rom_3_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_3_2/system_rom_3_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_3_3/system_rom_3_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_3_4/system_rom_3_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_3_5/system_rom_3_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_3_6/system_rom_3_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_3_7/system_rom_3_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_0_0/system_rom_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_R_0/system_rom_R_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_R_1/system_rom_R_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_R_2/system_rom_R_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_R_3/system_rom_R_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_omega_0/system_rom_omega_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/ip/system_rom_omega_1/system_rom_omega_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/ip/top_lcd_display_0_0/sources_1/bd/system/system_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/top_ooc.xdc]
set_property is_locked true [get_files C:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/sources_1/bd/top/top.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/constrs_1/imports/new/lcd.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Documents/GitHub/Resistor-Capacitance-Inductance-Measurement-System/Display/lcd_test/lcd_test.srcs/constrs_1/imports/new/lcd.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef top_wrapper.dcp

catch { report_utilization -file top_wrapper_utilization_synth.rpt -pb top_wrapper_utilization_synth.pb }
