// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Wed Nov 29 11:23:20 2017

top top_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rstn(rstn_sig) ,	// input  rstn_sig
	.lcd_de(lcd_de_sig) ,	// output  lcd_de_sig
	.lcd_dclk(lcd_dclk_sig) ,	// output  lcd_dclk_sig
	.lcd_hsync(lcd_hsync_sig) ,	// output  lcd_hsync_sig
	.lcd_vsync(lcd_vsync_sig) ,	// output  lcd_vsync_sig
	.lcd_r(lcd_r_sig) ,	// output [7:0] lcd_r_sig
	.lcd_g(lcd_g_sig) ,	// output [7:0] lcd_g_sig
	.lcd_b(lcd_b_sig) 	// output [7:0] lcd_b_sig
);

